export type SeedFirmResearch = {
  firmName: string;
  firmType: string;
  aum: string | null;
  founded: number | null;
  headquarters: string | null;
  description: string | null;
  investmentFocus: string | null;
  dealSize: string | null;
  notableDeals: string[];
  whatTheyLookFor: string | null;
  hiringTimeline: string | null;
  interviewProcess: string | null;
  culture: string | null;
  msuAlumni: string[];
  websiteUrl: string | null;
  linkedinUrl: string | null;
};

export const SEED_FIRM_RESEARCH: SeedFirmResearch[] = [
  {
    firmName: "Goldman Sachs",
    firmType: "IB",
    aum: "~$2.5T+ client assets (firm-wide)",
    founded: 1869,
    headquarters: "New York, NY",
    description:
      "Leading global investment bank known for top-tier M&A advisory, markets, and asset management. Recruiting is highly structured with strong technical bar.",
    investmentFocus: "M&A, ECM, DCM, financing, markets, alternatives",
    dealSize: "Mega-cap to large mid-market advisory",
    notableDeals: ["Major cross-border M&A", "Landmark IPOs and financings"],
    whatTheyLookFor:
      "Strong technicals, polish, teamwork, and clear motivation for banking; demonstrated leadership and analytical rigor.",
    hiringTimeline: "Summer: superdays in fall; FT cycles vary by region",
    interviewProcess:
      "HireVue or first round, multiple technicals, then superday with bankers; expect accounting, valuation, and market questions.",
    culture: "Intense, high standards, collaborative within teams; long hours during live deals.",
    msuAlumni: [],
    websiteUrl: "https://www.goldmansachs.com",
    linkedinUrl: "https://www.linkedin.com/company/goldman-sachs",
  },
  {
    firmName: "Morgan Stanley",
    firmType: "IB",
    aum: "Large global wealth + institutional footprint",
    founded: 1935,
    headquarters: "New York, NY",
    description:
      "Global investment bank with strength in equities, wealth management, and advisory. Strong training and broad deal exposure.",
    investmentFocus: "M&A, restructuring, equity underwriting, institutional sales & trading",
    dealSize: "Large-cap advisory and financing",
    notableDeals: ["Iconic tech and consumer M&A", "Major restructuring mandates"],
    whatTheyLookFor:
      "Technical foundation, communication skills, resilience, and genuine interest in markets and advisory.",
    hiringTimeline: "Campus recruiting fall for summer roles",
    interviewProcess: "First rounds, technical interviews, superday with senior bankers.",
    culture: "Meritocratic, fast-paced; strong emphasis on client service.",
    msuAlumni: [],
    websiteUrl: "https://www.morganstanley.com",
    linkedinUrl: "https://www.linkedin.com/company/morgan-stanley",
  },
  {
    firmName: "JPMorgan",
    firmType: "IB",
    aum: "One of the largest global banks by assets",
    founded: 2000,
    headquarters: "New York, NY",
    description:
      "Universal bank with leading investment banking franchise; broad balance sheet enables large financing packages.",
    investmentFocus: "M&A, leveraged finance, DCM, ECM, payments",
    dealSize: "Bulge-bracket scale across regions",
    notableDeals: ["Large LBO financings", "Cross-border strategic M&A"],
    whatTheyLookFor:
      "Analytical skills, client presence, adaptability across products, and interest in markets and banking.",
    hiringTimeline: "Summer recruiting concentrated in fall",
    interviewProcess: "Multiple rounds including technical and fit; superday with group mix.",
    culture: "Large firm with many subcultures; strong mobility across products.",
    msuAlumni: [],
    websiteUrl: "https://www.jpmorganchase.com",
    linkedinUrl: "https://www.linkedin.com/company/jpmorganchase",
  },
  {
    firmName: "KKR",
    firmType: "PE",
    aum: "Hundreds of billions in alternatives AUM (public filings)",
    founded: 1976,
    headquarters: "New York, NY",
    description:
      "Global investment firm spanning private equity, credit, real assets, and insurance solutions; known for operational value creation.",
    investmentFocus: "Buyouts, growth, credit, real estate, infrastructure",
    dealSize: "Large-cap LBOs and growth deals globally",
    notableDeals: ["Flagship buyouts across sectors", "Credit and capital markets platforms"],
    whatTheyLookFor:
      "Deal judgment, modeling depth, intellectual curiosity, and evidence of ownership mindset.",
    hiringTimeline: "On-cycle and off-cycle; timing varies by office",
    interviewProcess: "Case-style technicals, deal discussions, and partner meetings late stage.",
    culture: "High ownership, analytical, long-term oriented.",
    msuAlumni: [],
    websiteUrl: "https://www.kkr.com",
    linkedinUrl: "https://www.linkedin.com/company/kkr",
  },
  {
    firmName: "Blackstone",
    firmType: "PE",
    aum: "Among largest alternative asset managers globally",
    founded: 1985,
    headquarters: "New York, NY",
    description:
      "Diversified alternatives platform spanning private equity, real estate, credit, and hedge fund solutions.",
    investmentFocus: "Corporate PE, real estate, credit, GP stakes",
    dealSize: "Mega-cap transactions across strategies",
    notableDeals: ["Large take-privates", "Major real estate platforms"],
    whatTheyLookFor:
      "Sharp technicals, maturity, client-ready communication, and clear passion for investing.",
    hiringTimeline: "Highly competitive; early prep recommended",
    interviewProcess: "Multiple technical rounds, modeling tests possible, senior interviews.",
    culture: "Intense, polished, entrepreneurial within verticals.",
    msuAlumni: [],
    websiteUrl: "https://www.blackstone.com",
    linkedinUrl: "https://www.linkedin.com/company/blackstone-group",
  },
  {
    firmName: "Apollo",
    firmType: "PE",
    aum: "Large credit and hybrid alternatives platform",
    founded: 1990,
    headquarters: "New York, NY",
    description:
      "Known for credit, hybrid, and opportunistic investing with integrated origination; expanding insurance-linked capital.",
    investmentFocus: "Credit, hybrid value, opportunistic equity",
    dealSize: "From middle market to large cap depending on strategy",
    notableDeals: ["Complex credit and hybrid transactions"],
    whatTheyLookFor:
      "Structured finance intuition, comfort with downside cases, and disciplined underwriting.",
    hiringTimeline: "Rolling by team",
    interviewProcess: "Technical-heavy with credit and LBO angles.",
    culture: "Direct, analytical, returns-focused.",
    msuAlumni: [],
    websiteUrl: "https://www.apollo.com",
    linkedinUrl: "https://www.linkedin.com/company/apollo-global-management",
  },
  {
    firmName: "Carlyle",
    firmType: "PE",
    aum: "Global multi-strategy alternatives",
    founded: 1987,
    headquarters: "Washington, DC",
    description:
      "Global investment firm with corporate private equity, global credit, and real assets strategies.",
    investmentFocus: "Buyouts, aerospace/defense, healthcare, tech, credit",
    dealSize: "Mid-market to large-cap",
    notableDeals: ["Sector-defining buyouts and exits"],
    whatTheyLookFor: "Team fit, global mindset, modeling, and sector curiosity.",
    hiringTimeline: "Campus and experienced hire paths",
    interviewProcess: "Technical and fit; group-specific later rounds.",
    culture: "Collegiate with strong sector verticals.",
    msuAlumni: [],
    websiteUrl: "https://www.carlyle.com",
    linkedinUrl: "https://www.linkedin.com/company/the-carlyle-group",
  },
  {
    firmName: "Evercore",
    firmType: "IB",
    aum: "N/A (advisory-focused)",
    founded: 1995,
    headquarters: "New York, NY",
    description:
      "Leading independent investment bank focused on M&A advisory and restructuring with lean deal teams.",
    investmentFocus: "M&A, shareholder activism, restructuring",
    dealSize: "Mid-market to mega-cap advisory",
    notableDeals: ["High-profile strategic mandates"],
    whatTheyLookFor:
      "Technical excellence, stamina, client polish, and passion for advisory craft.",
    hiringTimeline: "Summer recruiting fall",
    interviewProcess: "Rigorous technicals; smaller class sizes vs. BB.",
    culture: "Lean teams, high responsibility early.",
    msuAlumni: [],
    websiteUrl: "https://www.evercore.com",
    linkedinUrl: "https://www.linkedin.com/company/evercore",
  },
  {
    firmName: "Centerview Partners",
    firmType: "IB",
    aum: "N/A (private partnership)",
    founded: 2006,
    headquarters: "New York, NY",
    description:
      "Elite independent M&A advisory partnership known for senior banker involvement and selective hiring.",
    investmentFocus: "Strategic M&A, defense, special situations",
    dealSize: "Often large-cap strategic",
    notableDeals: ["Landmark mergers and defense mandates"],
    whatTheyLookFor:
      "Exceptional judgment, maturity, technical depth, and evidence of long-term interest in M&A.",
    hiringTimeline: "Very small classes; highly selective",
    interviewProcess: "Deep technical and situational; multiple partner meetings.",
    culture: "Partnership model, high touch with clients.",
    msuAlumni: [],
    websiteUrl: "https://www.centerviewpartners.com",
    linkedinUrl: "https://www.linkedin.com/company/centerview-partners",
  },
  {
    firmName: "PJT Partners",
    firmType: "IB",
    aum: "N/A",
    founded: 2015,
    headquarters: "New York, NY",
    description:
      "Advisory-focused firm spanning strategic advisory, restructuring, and Park Hill placement.",
    investmentFocus: "M&A, restructuring, sponsor coverage",
    dealSize: "Varied; strong in complex situations",
    notableDeals: ["Complex M&A and restructuring roles"],
    whatTheyLookFor: "Technical strength, poise, and fit with lean teams.",
    hiringTimeline: "Small analyst classes",
    interviewProcess: "Technical + fit; restructuring track adds case depth.",
    culture: "Entrepreneurial advisory culture.",
    msuAlumni: [],
    websiteUrl: "https://www.pjtpartners.com",
    linkedinUrl: "https://www.linkedin.com/company/pjt-partners",
  },
  {
    firmName: "Warburg Pincus",
    firmType: "PE",
    aum: "Large global growth and buyout investor",
    founded: 1966,
    headquarters: "New York, NY",
    description:
      "Growth-oriented private equity with global sector teams and long hold periods in select themes.",
    investmentFocus: "Technology, healthcare, financial services, consumer",
    dealSize: "Growth to large buyouts",
    notableDeals: ["Growth equity and buyout platforms"],
    whatTheyLookFor: "Growth mindset, sector depth, and partnership approach.",
    hiringTimeline: "On-cycle and off-cycle",
    interviewProcess: "Technical + case discussions on portfolio themes.",
    culture: "Collaborative, globally integrated.",
    msuAlumni: [],
    websiteUrl: "https://www.warburgpincus.com",
    linkedinUrl: "https://www.linkedin.com/company/warburg-pincus",
  },
  {
    firmName: "Bain Capital",
    firmType: "PE",
    aum: "Large multi-strategy alternatives",
    founded: 1984,
    headquarters: "Boston, MA",
    description:
      "Private equity, credit, and public equity strategies with operational heritage from consulting roots.",
    investmentFocus: "Buyouts, tech, healthcare, credit",
    dealSize: "Mid to large cap",
    notableDeals: ["Cross-sector buyouts and credit platforms"],
    whatTheyLookFor: "Operator-investor lens, teamwork, and analytical rigor.",
    hiringTimeline: "Structured recruiting",
    interviewProcess: "Case + technical + culture fit.",
    culture: "Team-oriented, analytical.",
    msuAlumni: [],
    websiteUrl: "https://www.baincapital.com",
    linkedinUrl: "https://www.linkedin.com/company/bain-capital",
  },
  {
    firmName: "TPG",
    firmType: "PE",
    aum: "Global multi-platform alternatives",
    founded: 1992,
    headquarters: "Fort Worth, TX / San Francisco, CA",
    description:
      "Global alternative asset firm spanning private equity, growth, impact, and credit.",
    investmentFocus: "Buyouts, growth, climate, healthcare",
    dealSize: "Broad range globally",
    notableDeals: ["Large buyouts and growth platforms"],
    whatTheyLookFor: "Global perspective, sector curiosity, modeling.",
    hiringTimeline: "Campus + experienced",
    interviewProcess: "Technical + fit + case.",
    culture: "Growth-oriented and thematic.",
    msuAlumni: [],
    websiteUrl: "https://www.tpg.com",
    linkedinUrl: "https://www.linkedin.com/company/tpg",
  },
  {
    firmName: "Ares Management",
    firmType: "PE",
    aum: "Large credit and alternative credit platform",
    founded: 1997,
    headquarters: "Los Angeles, CA",
    description:
      "Credit-led alternatives manager with direct lending, special situations, and private equity strategies.",
    investmentFocus: "Direct lending, special sits, PE",
    dealSize: "MM to large direct lending",
    notableDeals: ["Direct lending and opportunistic credit"],
    whatTheyLookFor: "Credit skills, structuring, risk awareness.",
    hiringTimeline: "Team-dependent",
    interviewProcess: "Credit + LBO technical mix.",
    culture: "Structured finance heavy.",
    msuAlumni: [],
    websiteUrl: "https://www.aresmgmt.com",
    linkedinUrl: "https://www.linkedin.com/company/ares-management",
  },
  {
    firmName: "Lazard",
    firmType: "IB",
    aum: "N/A",
    founded: 1848,
    headquarters: "New York, NY",
    description:
      "Historic advisory franchise with global M&A and restructuring strength.",
    investmentFocus: "M&A, restructuring, asset management",
    dealSize: "Large-cap advisory",
    notableDeals: ["Landmark cross-border M&A"],
    whatTheyLookFor: "Technicals, languages a plus, maturity.",
    hiringTimeline: "Fall campus",
    interviewProcess: "Technical rounds + superday.",
    culture: "Advisory heritage, international.",
    msuAlumni: [],
    websiteUrl: "https://www.lazard.com",
    linkedinUrl: "https://www.linkedin.com/company/lazard",
  },
  {
    firmName: "Sequoia Capital",
    firmType: "VC",
    aum: "N/A (VC fund sizes vary by vintage)",
    founded: 1972,
    headquarters: "Menlo Park, CA",
    description:
      "Leading venture capital firm backing iconic technology companies from seed to growth globally.",
    investmentFocus: "Software, AI, consumer, fintech, healthcare",
    dealSize: "Seed through growth",
    notableDeals: ["Major technology platform investments"],
    whatTheyLookFor:
      "Product intuition, founder empathy, market selection, and evidence of hustle.",
    hiringTimeline: "Highly competitive; small teams",
    interviewProcess: "Case studies on markets and products; partner judgment heavy.",
    culture: "Founder-aligned, long-term horizon.",
    msuAlumni: [],
    websiteUrl: "https://www.sequoiacap.com",
    linkedinUrl: "https://www.linkedin.com/company/sequoia",
  },
  {
    firmName: "Andreessen Horowitz",
    firmType: "VC",
    aum: "N/A",
    founded: 2009,
    headquarters: "Menlo Park, CA",
    description:
      "Multi-stage venture and growth investor with strong platform support for portfolio companies.",
    investmentFocus: "Crypto, enterprise, consumer, bio",
    dealSize: "Seed through growth",
    notableDeals: ["High-profile tech and crypto ecosystem bets"],
    whatTheyLookFor: "Thematic depth, network, and founder support mindset.",
    hiringTimeline: "Rolling",
    interviewProcess: "Market + founder + product sense.",
    culture: "Content-forward, operator network.",
    msuAlumni: [],
    websiteUrl: "https://a16z.com",
    linkedinUrl: "https://www.linkedin.com/company/a16z",
  },
  {
    firmName: "Moelis & Company",
    firmType: "IB",
    aum: "N/A",
    founded: 2007,
    headquarters: "Los Angeles, CA",
    description:
      "Independent investment bank focused on M&A, restructuring, and capital markets advisory.",
    investmentFocus: "M&A, restructuring, capital advisory",
    dealSize: "Mid to large cap",
    notableDeals: ["Restructuring and M&A mandates"],
    whatTheyLookFor: "Technical + client polish + resilience.",
    hiringTimeline: "Fall recruiting",
    interviewProcess: "Technical-heavy superdays.",
    culture: "Entrepreneurial independent bank.",
    msuAlumni: [],
    websiteUrl: "https://www.moelis.com",
    linkedinUrl: "https://www.linkedin.com/company/moelis---company",
  },
];
