import type { Prisma } from "@prisma/client";

/** Approximate 2026 cycle placeholders — always verify on firm sites. */
export const SEED_RECRUITING_CALENDAR: Prisma.RecruitingCalendarEventCreateManyInput[] = [
  {
    title: "Goldman Sachs Apps Open",
    firmName: "Goldman Sachs",
    vertical: "IB",
    eventType: "Apps Open",
    date: new Date("2026-08-15T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-gs-apps-open",
    notes: "Approximate — verify on Goldman careers.",
  },
  {
    title: "Goldman Sachs Apps Close",
    firmName: "Goldman Sachs",
    vertical: "IB",
    eventType: "Apps Close",
    date: new Date("2026-10-15T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-gs-apps-close",
    notes: "Approximate — verify on Goldman careers.",
  },
  {
    title: "Morgan Stanley Apps Open",
    firmName: "Morgan Stanley",
    vertical: "IB",
    eventType: "Apps Open",
    date: new Date("2026-08-10T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-ms-apps-open",
  },
  {
    title: "JPMorgan Apps Open",
    firmName: "JPMorgan",
    vertical: "IB",
    eventType: "Apps Open",
    date: new Date("2026-08-12T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-jpm-apps-open",
  },
  {
    title: "KKR On-Cycle Start",
    firmName: "KKR",
    vertical: "PE",
    eventType: "On-Cycle Start",
    date: new Date("2026-09-01T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-kkr-oncycle",
  },
  {
    title: "Blackstone On-Cycle Start",
    firmName: "Blackstone",
    vertical: "PE",
    eventType: "On-Cycle Start",
    date: new Date("2026-09-05T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-bx-oncycle",
  },
  {
    title: "Apollo On-Cycle Start",
    firmName: "Apollo",
    vertical: "PE",
    eventType: "On-Cycle Start",
    date: new Date("2026-09-08T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-apollo-oncycle",
  },
  {
    title: "Evercore Apps Open",
    firmName: "Evercore",
    vertical: "IB",
    eventType: "Apps Open",
    date: new Date("2026-09-01T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-evercore-apps-open",
  },
  {
    title: "Centerview Apps Open",
    firmName: "Centerview",
    vertical: "IB",
    eventType: "Apps Open",
    date: new Date("2026-09-03T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-centerview-apps-open",
  },
  {
    title: "PE@Broad Info Session",
    firmName: "MSU / Broad",
    vertical: "PE",
    eventType: "Info Session",
    date: new Date("2026-09-20T12:00:00.000Z"),
    year: 2026,
    verified: false,
    dedupeKey: "seed-2026-pe-broad-info",
    notes: "Campus org — confirm dates with club.",
  },
];
