/** Banks shown in mock interview filters (SHARED question bank is keyed by these names). */
export const MOCK_INTERVIEW_BANKS = [
  "Case in Point / General Consulting",
  "Goldman Sachs",
  "Morgan Stanley",
  "JPMorgan",
  "KKR",
  "Blackstone",
  "Apollo",
  "Evercore",
  "Centerview",
  "PJT",
  "Carlyle",
  "Warburg Pincus",
  "Bain Capital",
  "TPG",
  "Ares",
  "Lazard",
  "Moelis",
  "Houlihan Lokey",
  "Rothschild",
  "William Blair",
  "Baird",
  "Lincoln International",
  "Raymond James",
  "Piper Sandler",
] as const;
